/*
 * File: checkPrompt.c
 * Description: Check the properties of standard input to determine
 *              whether we should print the prompt.
 *
 * XXX DO NOT EDIT THIS FILE.
 */
#include <sys/stat.h>
#include <unistd.h> /* for STDIN_FILENO */

#include "pa2.h" /* Contains prototype for function */


/*
 * Function Name: checkPrompt()
 * Function Prototype: short checkPrompt()
 * Description: Checks the file information on stdin using its file descriptor.
 *              Determines the type of stdin and returns whether prompt should
 *              be printed or not.
 * Parameters: None
 * Side Effects: None
 * Error Conditions: None
 * Return Value: 1 if prompt should be diplayed, 0 if it should not
 */
short checkPrompt() {

  /* Get information about STDIN */
  struct stat stdinstat;
  (void) fstat( STDIN_FILENO, &stdinstat );

  /* Check what STDIN is */
  switch( stdinstat.st_mode & S_IFMT ) {
    case S_IFCHR:  /* stdin coming from terminal. Is character device */ 
      return TRUE;
    case S_IFREG:  /* stdin being redirected to file. Is regular file */
    case S_IFIFO:  /* stdin being piped. Is a FIFO/Pipe */
      return FALSE;
    default:       /* Some magic just happened and the world is going to end */
      return TRUE;
  }
}
